name: Feature Request
description: Request a new feature to be added to the game.
title: "Feat: "
labels: ["type: feature request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: input
    id: feature-request-title
    attributes:
      label: What feature would you like to see added in one sentence?
    validations:
      required: true
  - type: textarea
    id: feature-request-body
    attributes:
      label: Elaborate on your request above as needed.
      placeholder: Tell us why this feature should be added!
      value: |
        ...

        <!-- Use the checklist below to track the progress of your feature request.
        Some entries may also become separate GitHub issues. -->
        <!-- #### Checklist
         - [ ] ...
         - [ ] ...
         -->
    validations:
      required: true
  - type: dropdown
    id: aspect
    attributes:
      label: Which aspect(s) of the project is this enhancement affecting?
      description: See [this wiki page](https://github.com/sloukit/pydew-valley-uzh/wiki/How-to-choose-labels) for more information on how to choose labels.
      multiple: true
      options:
        - game-art
        - game-audio       
        - game-design      
        - game-level-design
        - game-ui          
        - game-gameplay          
        - game-playtesting     
        - game-ai          
        - game-help        
        - game-story 
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
